### ISSUE TITLE
Snapshot file name, location changes

### ISSUE THREAD

**Issue by DifferentComputers** [FlyingDiver/Indigo-Camect#1]
The current destination of any snapshot file is at the root of the Indigo Web Server folder. This folder is not designed to serve files aside from favicons and similar low level resources. The public folder located inside the web server folder is a much better target.

Alternately, being able to specify a folder location for a snapshot image would be useful.

**Comment by FlyingDiver** [comment]
Split naming to #2

**Comment by FlyingDiver** [comment]
In 0.0.4
