### ISSUE TITLE
   Camect Warning                  Camera System: snapshotCameraCommand KeyError: ''

### ISSUE THREAD

**Issue by DifferentComputers** [FlyingDiver/Indigo-Camect#11]
`   Camect Warning                  Camera System: snapshotCameraCommand KeyError: ''`

How can I troubleshoot this? This recurs occasionally, even after reloading the plugin and confirming cameras are working inside Camect.

**Comment by FlyingDiver** [comment]
First, turn on debug logging.  That will give additional info.

**Comment by FlyingDiver** [comment]
I'll have to look at it when I get back from vacation, which will be a few weeks.

**Comment by DifferentComputers** [comment]
Have a great time!

**Comment by FlyingDiver** [comment]
Not enough info to track down.  The command is referring to a camera ID that's not currently in the system.
