### ISSUE TITLE
 exception in device_start_comm(Camera System): 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by DifferentComputers** [FlyingDiver/Indigo-Camect#12]
If a camera has dropped off from connectivity to Camect and Indigo requests camect to access it, this happens` exception in device_start_comm(Camera System): 'NoneType' object has no attribute 'json' `

And the camect plugin sometimes(?) does not recover from this problem. So far I’ve only been able to make this go away by restarting the Camect hardware.

**Comment by FlyingDiver** [comment]
Unable to reproduce.
