### ISSUE TITLE
"IndigoWebServer" folder is now "Web Assets"

### ISSUE THREAD

**Issue by DifferentComputers** [FlyingDiver/Indigo-Camect#4]
in 2021.1, the name of the web server folder has changed. snapshots can no longer find the path to the public folder.

**Comment by FlyingDiver** [comment]
Understood.  Will look at ASAP.

**Comment by FlyingDiver** [comment]
Just change the path in the plugin config dialog.  I'll change the default in the next release.

**Comment by FlyingDiver** [comment]
Updated in 0.0.6
